- name: create local {{ create_ssl_dir }}
  file:
    path: "{{ create_ssl_dir }}"
    state: directory
    directory_mode: 755

- name: cp admin-csr.json to {{ create_ssl_dir }}
  copy:
    src: files/{{ item }}
    dest: "{{ create_ssl_dir }}"
  with_items:
    - "{{ admin_csr_json }}"

- name: create admin.pem
  shell: |
    :;{{ cfssl_path }}/cfssl gencert \
       -ca={{ create_ssl_dir }}/ca.pem \
       -ca-key={{ create_ssl_dir }}/ca-key.pem \
       -config={{ create_ssl_dir }}/ca-config.json \
       -profile=kubernetes \
       {{ admin_csr_json }} | {{ cfssl_path }}/cfssljson -bare admin;
  args:
    chdir: "{{ create_ssl_dir }}"
