- name: start kube-apiserver
  systemd:
    name: kube-apiserver
    daemon_reload: yes
    state: started
    enabled: yes
- name: start kube-controller-manager
  systemd:
    name: kube-controller-manager
    daemon_reload: yes
    state: started
    enabled: yes
- name: start kube-scheduler
  systemd:
    name: kube-scheduler
    daemon_reload: yes
    state: started
    enabled: yes
