kind: Service
apiVersion: v1
metadata:
  name: ingress
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    name: http
  - protocol: TCP
    port: 443
    name: https
  selector:
    k8s-app: nginx-ingress-controller
