- name: install_from_source | download flannel file
  get_url: url={{ flannel_file_url }} dest=/tmp/{{ flannel_version }} validate_certs=no
  when: inventory_hostname in groups['local']

- name: scp {{ flannel_version }} to nodes
  copy:
    src: "/tmp/{{ flannel_version }}"
    dest: "/tmp/"
    mode: u+x

- name: yum install flannel
  yum: name={{item}}
  with_items:
     - /tmp/{{ flannel_version }}

- name: scp flanneld conf to node
  template: src={{ item.src }} dest={{ item.dest }}/{{ item.src.split('.')[:-1]|join('.') }}
  with_items:
    - { src: 'flanneld.j2', dest: '/etc/sysconfig/' }
    - { src: 'flannel.conf.j2', dest: '/etc/systemd/system/docker.service.d/' }
