- copy:
    src: files/{{ item }}
    dest: "{{ kubernetes_path }}/temp"
  with_items:
    - 'coredns.yaml'
    - 'dns-auto-scaling.yaml'

- name: deploy coredns
  shell: |
    :;{{ kubelet_bin_path }}/kubectl apply -f {{ kubernetes_path }}/temp/coredns.yaml;
    {{ kubelet_bin_path }}/kubectl apply -f {{ kubernetes_path }}/temp/dns-auto-scaling.yaml;
 
