- name: 本地创建创建create_ssl_dir
  file:
    path: "{{ create_ssl_dir }}"
    state: directory
    directory_mode: 755

- name: 复制ca*.json到本地目标文件夹
  copy:
    src: files/{{ item }}
    dest: "{{ create_ssl_dir }}"
  with_items:
    - "{{ etcd_csr_json }}"

- name: 生成 CA 证书和私钥
  shell: |
    :;{{ cfssl_path }}/cfssl gencert \
       -ca={{ create_ssl_dir }}/ca.pem \
       -ca-key={{ create_ssl_dir }}/ca-key.pem \
       -config={{ create_ssl_dir }}/ca-config.json \
       -hostname={{ VIP }},127.0.0.1,10.254.0.1,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.default.svc.cluster.local,{% for host in groups['Etcd'] %}{{ hostvars[host].ansible_default_ipv4.address }}{% if not loop.last %},{% endif %}{% endfor %} \
       -profile=kubernetes \
       {{ etcd_csr_json }} | {{ cfssl_path }}/cfssljson -bare etcd;
  args:
    chdir: "{{ create_ssl_dir }}"
