- name: 本地创建创建create_ssl_dir
  file:
    path: "{{ create_ssl_dir }}"
    state: directory
    directory_mode: 755

- name: 复制ca*.json到本地目标文件夹
  copy:
    src: files/{{ item }}
    dest: "{{ create_ssl_dir }}"
  with_items:
    - "{{ ca_config_json }}"
    - "{{ ca_csr_json }}"

- name: 生成 CA 证书和私钥
  shell: |
    :;{{ cfssl_path }}/cfssl gencert -initca {{ ca_csr_json }} | {{ cfssl_path }}/cfssljson -bare {{ ca }};
  args:
    chdir: "{{ create_ssl_dir }}"

