---
- name: create etcd conf path
  file:
    path: "{{ item }}"
    state: directory
    owner: etcd
    group: etcd
  with_items:
    - "{{ etcd_conf_path }}"

- name: create etcd systemd unit file
  template: 
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    
- name: create etcd env conf
  template: 
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    owner: etcd
    group: etcd
    mode: 0540
    
