- name: install_from_source | download etcd file
  get_url: url={{ etcd_file_url }} dest=/tmp/{{ etcd_version }}.tgz validate_certs=no
  when: inventory_hostname in groups['local']

- name: 解压
  unarchive:
    src: /tmp/{{ etcd_version }}.tgz
    dest: /tmp/
  when: inventory_hostname in groups['local']

- name: cp bin to "{{ etcd_bin_path }}"
  copy:
    src: "{{ item }}"
    dest: "{{ etcd_bin_path }}"
    owner: etcd
    group: etcd
    mode: 0750
  with_items:
    - "/tmp/{{ etcd_version }}/etcd"
    - "/tmp/{{ etcd_version }}/etcdctl"
  when: inventory_hostname in groups['Etcd']
